name: SigmaSecurity
version: @version@
authors: [DevTuca, DevKeni]
main: com.serversigma.SigmaSecurity


commands:
  security:
    description: "2FA for admins."
    aliases: [sec, logarstaff, ls, loginstaff]

  setsecurity:
      description: "Defina a 2FA password"
      aliases: [setsec, setls, setloginstaff, setlogarstaff]

